import localFont from "next/font/local";
import SessionWrapper from "@/components/SessionWrapper";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Recipe Archives",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          style={{
            backgroundImage: 'url("/assets/Image/bg1.jpg")',
            backgroundSize: "cover",
            backgroundAttachment: "fixed",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
          }}
          className={`${geistSans.variable} ${geistMono.variable} antialiased p-2 flex justify-center items-center w-full h-full`}
        >
          <div className="max-w-[1260px] w-full">
            <ToastContainer />
            {children}
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
